/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

    ControllerSidebar: [{type: 'autogenerated', dirName: 'download' }],
    tuningSidebar: [{ type: 'autogenerated', dirName: 'Tuning' }],
    manufactSidebar: [{ type: 'autogenerated', dirName: 'Manufacturers' }],
    developSidebar: [{ type: 'autogenerated', dirName: 'Contributing' }],
    tutorialSidebar: [{ type: 'autogenerated', dirName: 'Wiki' }]
};

module.exports = sidebars;
